IF
  Contains("MISCBP",Myself)
  Global("HaveHeart","AR1401",0)
THEN
    RESPONSE #100
      SetGlobal("HaveHeart","AR1401",1)
      Continue()
END

IF
  Contains("solabody",Myself) // Anomen's Body
  Global("HaveHeart","AR1401",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        //SetGlobal("CleanseVampire","AR1401",2)
        DestroyItem("solabody") // Anomen's Body
        SetGlobal("SolaBackFromDead","GLOBAL",1)
        CreateVisualEffect("SPMETSW2",[2592.1701])
        CreateVisualEffect("SPMETSW2",[2645.1742])
        Wait(1)
        CreateVisualEffect("SPFLESHS",[2565.1677])
        Wait(1)
        //ActionOverride("Sola",ChangeAIScript("sola",OVERRIDE))
        //ActionOverride("Sola",SetDialog("sola"))
        MoveGlobal("AR1401","Sola",[2565.1677])
        SetInterrupt(TRUE)
END
