IF
    Dead("solae1")
    Dead("solae2")
    Dead("solae3")
    Dead("solae4")
    Dead("solae5")
    Dead("solae6")
THEN
    RESPONSE #100
        DestroySelf()
END

IF
    OR(6)
        !Dead("solae1")
        !Dead("solae2")
        !Dead("solae3")
        !Dead("solae4")
        !Dead("solae5")
        !Dead("solae6")
    GlobalTimerExpired("SolaEclipseTimeStop","GLOBAL")
    Difficulty(EASIEST)
THEN
    RESPONSE #100
        SetGlobalTimer("SolaEclipseTimeStop","GLOBAL",24)
        ReallyForceSpell(Myself,4995)
END

IF
    OR(6)
        !Dead("solae1")
        !Dead("solae2")
        !Dead("solae3")
        !Dead("solae4")
        !Dead("solae5")
        !Dead("solae6")
    GlobalTimerExpired("SolaEclipseTimeStop","GLOBAL")
    Difficulty(EASY)
THEN
    RESPONSE #100
        SetGlobalTimer("SolaEclipseTimeStop","GLOBAL",18)
        ReallyForceSpell(Myself,4995)
END

IF
    OR(6)
        !Dead("solae1")
        !Dead("solae2")
        !Dead("solae3")
        !Dead("solae4")
        !Dead("solae5")
        !Dead("solae6")
    GlobalTimerExpired("SolaEclipseTimeStop","GLOBAL")
    !Difficulty(EASY)
    !Difficulty(EASIEST)
THEN
    RESPONSE #100
        SetGlobalTimer("SolaEclipseTimeStop","GLOBAL",12)
        ReallyForceSpell(Myself,4995)
END
