/////////////////////////////////////////////////////////////////////
// boo2
// "Boo Two" the Familiar. Basically, he just hides in shadows and
// detects traps for you. 
/////////////////////////////////////////////////////////////////////

IF 
  Global("Prep","LOCALS",0)     // whenever I am created
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    AddSpecialAbility("boo2cap")
    Ally()
END

IF
  Global("SolaBooFirstTime","GLOBAL",1)
THEN
  RESPONSE #100
    StartDialogueNoSet(Player1)
END


// I went back to the party
IF
  CheckStat(Myself,22,WIS)
THEN
  RESPONSE #100
    DestroyItem("MEL01")
    DestroySelf()
END


// I'm dying, run to Jan!
IF
  HPLT(Myself,2)
  Detect("Jan")
THEN
  RESPONSE #100
    ActionOverride("Jan",AddSpecialAbility("boo2free"))
    DestroyItem("MEL01")
    DestroySelf()
END

// I'm dying, run to Player1
IF
  HPLT(Myself,2)
  !Detect("Jan")
THEN
  RESPONSE #100
    ActionOverride(Player1,AddSpecialAbility("boo2free"))
    DestroyItem("MEL01")
    DestroySelf()
END

// teleport to the PC
IF
  !InMyArea(Player1)
THEN
  RESPONSE #100
    MoveGlobalObject(Myself,Player1)
END

// * HIDE *
IF
	ActionListEmpty()
	!StateCheck(Myself,STATE_INVISIBLE)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
	      Hide()
END

// * FIND TRAPS *
IF
	ActionListEmpty()
	!ModalState(DETECTTRAPS)
THEN
	RESPONSE #100
		FindTraps()
END
