//////////////////////////////////////////////////////////////////////////
// Solaufein Romance Mod Pack
// Westley Weimer     <weimer@cs.berkeley.edu>
//////////////////////////////////////////////////////////////////////////
// 
// See Readme-SolaRomance.txt for a high-level description of what is going
// on here. 
//////////////////////////////////////////////////////////////////////////
IF
  !InParty(Myself)
  InPartyAllowDead(Myself)
THEN
  RESPONSE #100
END

// give more XP 
IF
    Global("SolaPortPower","GLOBAL",0)
    XPGT(Player1,1750000)
THEN
  RESPONSE #100
    AddXPObject(Myself,500000)
    Continue()
END

IF
    Global("SolaPortPower","GLOBAL",0)
    XPGT(Player1,2250000)
THEN
  RESPONSE #100
    AddXPObject(Myself,500000)
    Continue()
END

IF
    Global("SolaPortPower","GLOBAL",0)
    XPGT(Player1,2750000)
THEN
  RESPONSE #100
    AddXPObject(Myself,500000)
    Continue()
END

IF
    Global("SolaPortPower","GLOBAL",0)
    XPGT(Player1,3250000)
THEN
  RESPONSE #100
    AddXPObject(Myself,500000)
    Continue()
END

// Give him that magic teleport power and other initial items
IF
    Global("SolaPortPower","GLOBAL",0)
THEN
    RESPONSE #100
        AddSpecialAbility("dimdoor")
        GiveItemCreate("sw1h06",Myself,1,0,0)  // long + 2
        GiveItemCreate("solabook",Myself,1,0,0)  // long + 2
        GiveItemCreate("helm04",Myself,1,0,1)  // defense
        GiveItemCreate("ring02",Myself,1,0,1)  // fire res
        GiveItemCreate("scrl1v",Myself,1,0,0)  // stoneskin
        GiveItemCreate("scrl7k",Myself,1,0,0)  // mislead
        GiveItemCreate("scrl7o",Myself,1,0,0)  // pro-magic
        GiveItemCreate("scrl75",Myself,5,0,0)  // identify
        GiveItemCreate("potn28",Myself,10,0,0)  // potion of fortitude
        GiveItemCreate("wand05",Myself,15,15,1)  // fire
        IncrementGlobal("SolaPortPower","GLOBAL",1)
END

// did we just raise him? 
IF 
  Global("SolaBackFromDead","GLOBAL",1)
THEN
  RESPONSE #100
    SetDialog("Sola")
    StartDialogueNoSet(Player1)
END

// with Sola gone, you look spiffier
IF
    !InParty(Myself)
    Global("SolaRepLoss","GLOBAL",1)
THEN
    RESPONSE #100
      SetGlobal("SolaRepLoss","GLOBAL",0)
      ReputationInc(2)
END

// If this is the first time new-Solaufein is meeting <CHARNAME>, 
// initiate dialogue and offer to join. 
IF
    Global("SolaJoin","GLOBAL",0)
    NumTimesTalkedTo(0)
    Range(Player1,12)
THEN
    RESPONSE #100
        StartDialogueNoSet(Player1)
END

// Solaufein is a drow! Lose Rep!
IF
    OR(2)
      Global("SolaJoin","GLOBAL",1)
      Global("SolaJoin","GLOBAL",5)
    ReputationGT(Player1,10)
    !Global("SolaRepLoss","GLOBAL",1)
THEN
    RESPONSE #100
        ReputationInc(-2)
        SetGlobal("SolaRepLoss","GLOBAL",1)
        Continue()
END

// this is not the first time we're joining
IF
    Global("SolaJoin","GLOBAL",5)
THEN
    RESPONSE #100
      SetGlobal("SolaJoin","GLOBAL",2)
      SetGlobal("SolaLeave","GLOBAL",0)
      RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
      JoinParty()
END

// if the player asked us to join up, do it!
// If the player is Evil, we become Neutral
IF
    Global("SolaJoin","GLOBAL",1)
    OR(3)
      Alignment(Player1,LAWFUL_EVIL)
      Alignment(Player1,NEUTRAL_EVIL)
      Alignment(Player1,CHAOTIC_EVIL)
THEN  
    RESPONSE #100
        SetGlobal("SolaJoin","GLOBAL",2)
        SetGlobal("SolaLeave","GLOBAL",0)
        RealSetGlobalTimer("SolaTimer","GLOBAL",120) // short!
        ChangeAlignment(Myself,CHAOTIC_NEUTRAL)
        SetDialog("Sola")
        RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
        JoinParty()
END

// if the player asked us to join up, do it!
// If the player is not Evil, we just join
IF
    Global("SolaJoin","GLOBAL",1)
    !Alignment(Player1,LAWFUL_EVIL)
    !Alignment(Player1,NEUTRAL_EVIL)
    !Alignment(Player1,CHAOTIC_EVIL)
THEN  
    RESPONSE #100
        SetGlobal("SolaJoin","GLOBAL",2)
        RealSetGlobalTimer("SolaTimer","GLOBAL",120) // short!
        SetDialog("Sola")
        RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
        JoinParty()
END

// Advance the Solaufein romance. When SolaTimer goes off we Dialogue with
// the player. The dialogue tree will stop the romance by moving SolaTalk
// to -1. 
// This covers dialogue after JOINing but before SPIDERS.
IF
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    CombatCounter(0)
    !Range([NEUTRAL],10)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    OR(5)
        Global("SolaTalk","GLOBAL",1)   //  2=what shall I call you?
        Global("SolaTalk","GLOBAL",2)   //  3=childhood
        Global("SolaTalk","GLOBAL",3)   //  4=phaere mask? 
        Global("SolaTalk","GLOBAL",4)   //* 5=inherent good/evil
        Global("SolaTalk","GLOBAL",5)   //  6=eilistraee
THEN
    RESPONSE #100
        IncrementGlobal("SolaTalk","GLOBAL",1)
        SetGlobal("SolaPCTalk","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        PlaySong(63)
        StartDialogueNoSet(Player1)
END

// Advance the Solaufein romance. When SolaTimer goes off we Dialogue with
// the player. The dialogue tree will stop the romance by moving SolaTalk
// to -1. 
// This covers dialogue after SPIDERS but before FOE.
IF
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    CombatCounter(0)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    InParty(Myself)
    See(Player1)
    !Range([NEUTRAL],10)
    Global("SolaSpiderSpawn","GLOBAL",4)  // spiders summoned
    OR(4)
        Global("SolaTalk","GLOBAL",6)   //* 7=free Ust Natha slaves
        Global("SolaTalk","GLOBAL",7)   //* 8=redemption poem
        Global("SolaTalk","GLOBAL",8)   //* 9=social contract   
        Global("SolaTalk","GLOBAL",9)   //* 10=summon = slavery 
THEN
    RESPONSE #100
        IncrementGlobal("SolaTalk","GLOBAL",1)
        SetGlobal("SolaPCTalk","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        PlaySong(63)
        StartDialogueNoSet(Player1)
END

// Advance the Solaufein romance. When SolaTimer goes off we Dialogue with
// the player. The dialogue tree will stop the romance by moving SolaTalk
// to -1. 
// This covers dialogue after FOE but before MOON.
IF
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    CombatCounter(0)
    !Range([NEUTRAL],10)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    Global("SolaFoeSpawn","GLOBAL",6)     // foe is dead
    OR(4)
        Global("SolaTalk","GLOBAL",10)  //* 11=traps and ambushes
        Global("SolaTalk","GLOBAL",11)  //  12=golem and prophecy
        Global("SolaTalk","GLOBAL",12)  //* 13=children and fire
        Global("SolaTalk","GLOBAL",13)  //  14=dance!
THEN
    RESPONSE #100
        IncrementGlobal("SolaTalk","GLOBAL",1)
        SetGlobal("SolaPCTalk","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        PlaySong(63)
        StartDialogueNoSet(Player1)
END

// Advance the Solaufein romance. When SolaTimer goes off we Dialogue with
// the player. The dialogue tree will stop the romance by moving SolaTalk
// to -1. 
// This covers dialogue after the REWARD/SLEEP. 
IF
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    CombatCounter(0)
    !Range([NEUTRAL],10)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    GlobalGT("SolaMoon","GLOBAL",4)   //  done with the moon thing!
    !Global("SolaSleep","GLOBAL",0)
    OR(5)
      Global("SolaTalk","GLOBAL",14)  //  15=safe to have a child?
      Global("SolaTalk","GLOBAL",15)  //  16=ravens are black 
      Global("SolaTalk","GLOBAL",16)  //  17=identity
      Global("SolaTalk","GLOBAL",17)  //  18=prophecy
      Global("SolaTalk","GLOBAL",18)  //  19=Sphira Chat
THEN
    RESPONSE #100
        IncrementGlobal("SolaTalk","GLOBAL",1)
        SetGlobal("SolaPCTalk","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        PlaySong(63)
        StartDialogueNoSet(Player1)
END

// More Solaufein romance dialogues. The Afi poem takes place at night. 
IF
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    CombatCounter(0)
    !Range([NEUTRAL],10)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    Global("SolaTalk","GLOBAL",19)  //  20=Afi poem
    PartyRested()
THEN
    RESPONSE #100
        IncrementGlobal("SolaTalk","GLOBAL",1)
        SetGlobal("SolaPCTalk","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        PlaySong(63)
        StartDialogueNoSet(Player1)
END

IF
  RealGlobalTimerExpired("SolaTimer","GLOBAL")
  CombatCounter(0)
  !Range([NEUTRAL],10)
  InParty(Myself)
  See(Player1)
  !Detect([ENEMY])
  !Detect([EVILBUTBLUE])
  !Global("SolaVampire","GLOBAL",0) // we were vamped! 
  GlobalGT("SolaTalk","GLOBAL",19) // ambition
  Global("SolaAmbitionTalk","GLOBAL",0)
THEN
  RESPONSE #100
      IncrementGlobal("SolaAmbitionTalk","GLOBAL",1)
      SetGlobal("SolaPCTalk","GLOBAL",1)
      RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
      PlaySong(63)
      StartDialogueNoSet(Player1)
END

// discuss the time: MORNING
IF
    TimeOfDay(3)  // MORNING
    Delay(30)
    OR(2)
    AreaType(OUTDOOR)
    AreaType(FOREST)
    Global("SolaDiscussMorning","GLOBAL",0)
    Global("SolaPCTalk","GLOBAL",0)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Range([NEUTRAL],10)
    CombatCounter(0)
    !AreaCheck("AR2500")
    !AreaCheck("AR4500")
    !AreaCheck("AR1404")
THEN
    RESPONSE #100
        IncrementGlobal("SolaDiscussMorning","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

IF
  InParty(Myself)
  See(Player1)
  !Detect([ENEMY])
  !Detect([EVILBUTBLUE])
  !Range([NEUTRAL],10)
  CombatCounter(0)
  !AreaCheck("AR2500")
  !AreaCheck("AR4500")
  !AreaCheck("AR1404")
  HasItem("solabk2",Myself)
  Global("SolaDiscussBook","GLOBAL",0)
  !Global("SolaTalk","GLOBAL",-1)
THEN
  RESPONSE #100
    SetGlobal("SolaDiscussBook","GLOBAL",1)
    RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
    StartDialogueNoSet(Player1)
END


// discuss the time: EVENING
IF
    TimeOfDay(1)  //dusk
    Delay(30)
    OR(2)
    AreaType(OUTDOOR)
    AreaType(FOREST)
    Global("SolaDiscussEvening","GLOBAL",0)
    Global("SolaPCTalk","GLOBAL",0)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Range([NEUTRAL],10)
    CombatCounter(0)
    !AreaCheck("AR2500")
    !AreaCheck("AR4500")
    !AreaCheck("AR1404")
THEN
    RESPONSE #100
        IncrementGlobal("SolaDiscussEvening","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

// discuss the time: WOODS
IF
    AreaType(FOREST)
    Delay(30)
    TimeOfDay(DAY)
    Global("SolaDiscussWoods","GLOBAL",0)
    Global("SolaPCTalk","GLOBAL",0)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Range([NEUTRAL],10)
    CombatCounter(0)
    !AreaCheck("AR2500")
    !AreaCheck("AR4500")
    !AreaCheck("AR1404")
THEN
    RESPONSE #100
        IncrementGlobal("SolaDiscussWoods","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

// still get the lunar reward, even if the PC hates us
IF
    Global("SolaTalk","GLOBAL",-1)    //  -1=no more romance
    Global("SolaFoeSpawn","GLOBAL",6)     //  done with the foe thing!
    Global("SolaMoonTimer","GLOBAL",0)
THEN
    RESPONSE #100
      RealSetGlobalTimer("SolaTimer","GLOBAL",13200)
      SetGlobal("SolaMoonTimer","GLOBAL",1)
END

// SolaMoon == 0 --> 1 <TALK> --> 2
// Tell the PC we should go outside to see the moon. 
IF
    Global("SolaMoon","GLOBAL",0)   //  moon!
    Global("SolaFoeSpawn","GLOBAL",6)   //  done with Archryssa
    OR(2)
      Global("SolaTalk","GLOBAL",14)  //  done with "dance" 
      Global("SolaTalk","GLOBAL",-1)  //  PC hates us
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Range([NEUTRAL],10)
    CombatCounter(0)
    OR(3)   
        !TimeOfDay(2)   // NIGHT
        AreaType(CITY)
        AreaType(DUNGEON)
THEN
    RESPONSE #100
        SetGlobal("SolaMoon","GLOBAL",1)
        StartDialogueNoSet(Player1)
        // SolaMoon is now 2
END

// SolaMoon == 2 --> 3 <TALK> --> 4
// Tell the PC to step away from the party. 
IF
    Global("SolaMoon","GLOBAL",2)   //  moon!
    TimeOfDay(2)  // NIGHT
    !AreaType(CITY)
    !AreaType(DUNGEON)
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Range([NEUTRAL],10)
    CombatCounter(0)
THEN
    RESPONSE #100
        SetGlobal("SolaMoon","GLOBAL",3)
        RealSetGlobalTimer("SolaRewardTimer","GLOBAL",30)
        StartDialogueNoSet(Player1)
        // SolaMoon is now 4
END

// SolaMoon == 4 --> 5 <TALK> --> 6,      SolaMoonPragma
// Look at the moon with the PC. Must be near the PC but away from the 
// others. 
// This is the original blade. 
IF
    Global("SolaMoon","GLOBAL",4)   //  do the moon thing!
    InParty(Myself)
    Detect(Player1)
    Range(Player1,5)
    RealGlobalTimerExpired("SolaRewardTimer","GLOBAL")
    !See([ENEMY])
    !See([EVILBUTBLUE])
    CombatCounter(0)
    !GlobalsGT("SolaRemorse","SolaPragma")  // sword reward
    TimeOfDay(2)  // NIGHT
    !AreaType(CITY)
    !AreaType(DUNGEON)
    !AreaCheck("AR4500")
    !XPGT(Myself,3500000)
THEN
    RESPONSE #100
        IncrementGlobal("SolaMoon","GLOBAL",1)
        StartCutSceneMode()
        MoveViewObject(Myself,2)
        SmallWait(7)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        CreateVisualEffectObject("spcrtwpn",Myself)
        GiveItemCreate("SolaBlad",Myself,1,0,0)
        EndCutSceneMode()
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

// SolaMoon == 4 --> 5 <TALK> --> 6,      SolaMoonPragma
// Look at the moon with the PC. Must be near the PC but away from the 
// others. 
// This is the upgraded blade. 
IF
    Global("SolaMoon","GLOBAL",4)   //  do the moon thing!
    InParty(Myself)
    Detect(Player1)
    Range(Player1,5)
    RealGlobalTimerExpired("SolaRewardTimer","GLOBAL")
    !See([ENEMY])
    !See([EVILBUTBLUE])
    CombatCounter(0)
    !GlobalsGT("SolaRemorse","SolaPragma")  // sword reward
    TimeOfDay(2)  // NIGHT
    !AreaType(CITY)
    !AreaType(DUNGEON)
    !AreaCheck("AR4500")
    XPGT(Myself,3500000)
THEN
    RESPONSE #100
        IncrementGlobal("SolaMoon","GLOBAL",1)
        StartCutSceneMode()
        MoveViewObject(Myself,2)
        SmallWait(7)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        CreateVisualEffectObject("spcrtwpn",Myself)
        GiveItemCreate("SolaBla2",Myself,1,0,0)
        EndCutSceneMode()
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

// SolaMoon == 4 --> 5 <TALK> --> 6,  SolaMoonRemorse
// Look at the moon with the PC. Must be near the PC but away from the 
// others. 
IF
    Global("SolaMoon","GLOBAL",4)   //  do the moon thing!
    InParty(Myself)
    Detect(Player1)
    Range(Player1,5)
    RealGlobalTimerExpired("SolaRewardTimer","GLOBAL")
    !See([ENEMY])
    !See([EVILBUTBLUE])
    CombatCounter(0)
    GlobalsGT("SolaRemorse","SolaPragma")   // blessing reward
    TimeOfDay(2) // NIGHT
    !AreaType(CITY)
    !AreaType(DUNGEON)
THEN
    RESPONSE #100
        IncrementGlobal("SolaMoon","GLOBAL",1)
        StartCutSceneMode()
        MoveViewObject(Myself,2)
        SmallWait(7)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        AddSpecialAbility("solaspl")
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        AddSpecialAbility("solaspl")
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        AddSpecialAbility("solaspl")
        Wait(1)
        ReallyForceSpell(Myself,4999) // SPCL999 = sola memorize
        Wait(1)
        EndCutSceneMode()
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        ChangeAlignment(Myself,CHAOTIC_GOOD)
        StartDialogueNoSet(Player1)
END

// After that, some nookie. SolaSleep!
IF
    Global("SolaMoon","GLOBAL",6)   //  done with the moon thing!
    !Global("SolaTalk","GLOBAL",-1)   //  PC likes us
    Global("SolaSleep","GLOBAL",0)
    TimeOfDay(2) // NIGHT
    InParty(Myself)
    See(Player1)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Detect([NEUTRAL])
    CombatCounter(0)
    AreaType(OUTDOOR)
    !AreaType(CITY)
    !AreaType(DUNGEON)
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
THEN
    RESPONSE #100
        SetGlobal("SolaSleep","GLOBAL",1)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

// Let's hit the hay!. Sleep -> 4 after the dialogue. 
IF
    Global("SolaSleep","GLOBAL",2)
THEN
    RESPONSE #100
        ActionOverride(Player1,Rest())
        ActionOverride(Player2,Rest())
        ActionOverride(Player3,Rest())
        ActionOverride(Player4,Rest())
        ActionOverride(Player5,Rest())
        ActionOverride(Player6,Rest())
        IncrementGlobal("SolaSleep","GLOBAL",1)
        StartDialogueNoSet(Player1)
END
        
// Foe #1 Nightmare:  SolaSpiderSpawn == 0 -> Talk -> 3
IF
    OR(2)
      Global("SolaTalk","GLOBAL",6)     //  6=eilistraee
      Global("SolaTalk","GLOBAL",-1)    //  -1=no more romance
    Global("SolaSpiderSpawn","GLOBAL",0)
    PartyRested()
    !AreaType(CITY)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Detect([NEUTRAL])
    InParty(Myself)
    See(Player1)
THEN
    RESPONSE #100
        SetGlobal("SolaSpiderSpawn","GLOBAL",2)
        SetGlobalTimer("SolaSpiderTimer","GLOBAL",18) // very short!
        StartDialogueNoSet(Player1)
END

// still face the big baddie, even if the PC hates us
IF
    Global("SolaSpiderSpawn","GLOBAL",4) // done with spiders
    Global("SolaTalk","GLOBAL",-1)       // -1=no more romance
    Global("SolaFoeSpawn","GLOBAL",0)    // do the foe thing!
    Global("SolaArchTimer","GLOBAL",0)
THEN
    RESPONSE #100
      RealSetGlobalTimer("SolaTimer","GLOBAL",13200)
      SetGlobal("SolaArchTimer","GLOBAL",1)
END

// Foe #1 appears!
IF    
    Global("SolaSpiderSpawn","GLOBAL",3)
    GlobalTimerExpired("SolaSpiderTimer","GLOBAL")
    LevelGT(Player1,11)
    !Difficulty(EASIEST)
    !Difficulty(EASY)
THEN
    RESPONSE #100
        StartCutSceneMode()
        CreateCreatureObjectDoor("spidph01",Myself,0,0,0)
        CreateCreatureObjectDoor("spidph01",Myself,0,0,0)
        Wait(2)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        IncrementGlobal("SolaSpiderSpawn","GLOBAL",1)
        EndCutSceneMode()
END

// Foe #1 appears! (weaker)
IF    
    Global("SolaSpiderSpawn","GLOBAL",3)
    GlobalTimerExpired("SolaSpiderTimer","GLOBAL")
    OR(3)
      !LevelGT(Player1,11)
      Difficulty(EASIEST)
      Difficulty(EASY)
THEN
    RESPONSE #100
        StartCutSceneMode()
        CreateCreatureObjectDoor("spidph01",Myself,0,0,0)
        Wait(2)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        IncrementGlobal("SolaSpiderSpawn","GLOBAL",1)
        EndCutSceneMode()
END
        
// time to face Archryssa? 
IF
    OR(2)
        Global("SolaTalk","GLOBAL",10)  //* 10=summon = slavery
        Global("SolaTalk","GLOBAL",-1)  // pc hates us
    Global("SolaFoeSpawn","GLOBAL",0)   // do the foe thing
    RealGlobalTimerExpired("SolaTimer","GLOBAL")
    Global("SolaSpiderSpawn","GLOBAL",4)// spiders already summoned
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    !Detect([NEUTRAL])
    CombatCounter(0)
    InParty(Myself)
    See(Player1)
THEN
    RESPONSE #100
        StartCutSceneMode()
        SetGlobal("SolaFoeSpawn","GLOBAL",2)
        CreateCreatureObjectDoor("solafoe",Myself,0,0,0) // Archryssa
        Wait(8)
        ActionOverride("solafoe",StartDialogueNoSet(Player1))
        Continue()
END


// gate out the party
IF
    Global("SolaFoeSpawn","GLOBAL",3)
    Detect(SecondNearest([PC]))
THEN
    RESPONSE #100
        CreateVisualEffectObject("SPDIMNDR",SecondNearest([PC]))
        CreateVisualEffectObject("SPDIMNDR",ThirdNearest([PC]))
        CreateVisualEffectObject("SPDIMNDR",FourthNearest([PC]))
        CreateVisualEffectObject("SPDIMNDR",FifthNearest([PC]))
        ActionOverride(SecondNearest([PC]),MoveBetweenAreas("AR0000",[0.0],0))
        ActionOverride(ThirdNearest([PC]),MoveBetweenAreas("AR0000",[0.0],0))
        ActionOverride(FourthNearest([PC]),MoveBetweenAreas("AR0000",[0.0],0))
        ActionOverride(FifthNearest([PC]),MoveBetweenAreas("AR0000",[0.0],0))
END

// gate back in the party when it's over!, SolaFoeSpawn -> 6 after talk
IF
    Global("SolaGateIn","GLOBAL",0)
    CombatCounter(0)
    Dead("SolaFoe")
THEN
    RESPONSE #100
        ClearAllActions()
        AddXPObject(Myself,50000)
        IncrementGlobal("SolaGateIn","GLOBAL",1)
        SetGlobal("SolaFoeSpawn","GLOBAL",5)
        MoveGlobalObjectOffScreen(Player1,Myself)
        MoveGlobalObjectOffScreen(Player2,Myself)
        MoveGlobalObjectOffScreen(Player3,Myself)
        MoveGlobalObjectOffScreen(Player4,Myself)
        MoveGlobalObjectOffScreen(Player5,Myself)
        MoveGlobalObjectOffScreen(Player6,Myself)
        CreateVisualEffectObject("SPDIMNDR",Player1)
        CreateVisualEffectObject("SPDIMNDR",Player2)
        CreateVisualEffectObject("SPDIMNDR",Player3)
        CreateVisualEffectObject("SPDIMNDR",Player4)
        CreateVisualEffectObject("SPDIMNDR",Player5)
        CreateVisualEffectObject("SPDIMNDR",Player6)
        RealSetGlobalTimer("SolaTimer","GLOBAL",3200)
        StartDialogueNoSet(Player1)
END

IF
    Global("SolaGateIn","GLOBAL",1)
    Global("SolaFoeSpawn","GLOBAL",5)
THEN
    RESPONSE #100
        StartDialogueNoSet(Player1)
END

// What if the PC kicks Sola out? 
IF
    Global("SolaJoin","GLOBAL",2)
    Global("SolaLeave","GLOBAL",0)
    !Detect([ENEMY])
    !Detect([EVILBUTBLUE])
    CombatCounter(0)
    !InParty(Myself)
THEN
    RESPONSE #100
        SetDialog("Sola")
        IncrementGlobal("SolaLeave","GLOBAL",1)
        // StartDialogueNoSet(Player1)
END

// teleport past the bad guys
IF
    AreaCheck("AR2401")
    Global("SolaTeleport","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("SolaTeleport","GLOBAL",1)
    StartDialogueNoSet(Player1)
END

IF
    Global("SolaTeleport","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("SolaTeleport","GLOBAL",3)
    CreateVisualEffectObject("SPDIMNDR",Myself)
    MoveBetweenAreas("ar2500",[300.300],0)
    LeaveParty()
END

IF
    Global("SolaJoin","GLOBAL",2)
    Global("SolaLeave","GLOBAL",2)
THEN
    RESPONSE #100
        IncrementGlobal("SolaLeave","GLOBAL",2)
        CreateVisualEffectObject("SPDIMNDR",Myself)
        MoveBetweenAreas("ar2500",[300.300],0)
END

///////////////////////////////////////////////////////////////////////
//                           Sola Party Banter
///////////////////////////////////////////////////////////////////////
// Aerie        1 dreamed ...
//              2 youth
// Anomen       1 anger
//              2 pride
// Cernd        1 animals eat each other in wild
//              2 state of nature = stupid
// Edwin        1 brain in vat
//              2 trade nether scroll for dimdoor
// Haer'Dalis   1 theatre / poetry
//              2 chaos / death 
// Imoen        1 soul
//              2 pick on Sola
// Jaheira      1 really balance? 
//              2 memory
// Jan          1 what is a turnip? 
//              2 boo two familiar
// Keldorn      1 law is organized violence
//              2 religion
// Korgan       1 violence
//              2 courage
// Mazzy        1 good of many / good of one
//              2 sacrifice
// Minsc        1 enough?
//              2 gardening
// Nalia        1 money
//              2 advice
// Sarevok      1 I'm not afraid of you
//              2 ask not for whom the bell tolls
// Valygar      1 reason
//              2 brood
// Viconia      1 resilience
//              2 evil
///////////////////////////////////////////////////////////////////////
// debugging!
IF
  RealGlobalTimerExpired("SolaBanter","GLOBAL")
  InParty(Myself)
  Global("SolaDoneBanter","GLOBAL",0)
  Global("SolaGoingToBanter","GLOBAL",0)
  Global("SolaPickingBanterTarget","GLOBAL",0)
  CombatCounter(0)

  // don't banter if there is someone on-screen you would mess up
  OR(2)
    !InMyArea("Aerie")
    InParty("Aerie")
  OR(2)
    !InMyArea("Anomen")
    InParty("Anomen")
  OR(2)
    !InMyArea("Cernd")
    InParty("Cernd")
  OR(2)
    !InMyArea("Edwin")
    InParty("Edwin")
  OR(2)
    !InMyArea("HaerDalis")
    InParty("HaerDalis")
  OR(2)
    !InMyArea("Imoen2")
    InParty("Imoen2")
  OR(2)
    !InMyArea("Jaheira")
    InParty("Jaheira")
  OR(2)
    !InMyArea("Keldorn")
    InParty("Keldorn")
  OR(2)
    !InMyArea("Korgan")
    InParty("Korgan")
  OR(2)
    !InMyArea("Mazzy")
    InParty("Mazzy")
  OR(2)
    !InMyArea("Minsc")
    InParty("Minsc")
  OR(2)
    !InMyArea("Nalia")
    InParty("Nalia")
  OR(2)
    !InMyArea("Sarevok")
    InParty("Sarevok")
  OR(2)
    !InMyArea("Valygar")
    InParty("Valygar")
  OR(2)
    !InMyArea("Viconia")
    InParty("Viconia")

THEN
  RESPONSE #100
    // DEBUG
    DisplayString(Myself,26926) // how do you pick these times to chat? 
    SetGlobal("SolaPickingBanterTarget","GLOBAL",1)
END

///////////////////////////////////////////////////////////////////////
// Pick a banter target. :-) 
///////////////////////////////////////////////////////////////////////
IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Aerie")
  !Global("Sola_Aerie","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Aerie","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Anomen")
  !Global("Sola_Anomen","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Anomen","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Cernd")
  !Global("Sola_Cernd","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Cernd","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Edwin")
  !Global("Sola_Edwin","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Edwin","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("HaerDalis")
  !Global("Sola_HD","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_HD","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Imoen2")
  !Global("Sola_Imoen","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Imoen","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Jaheira")
  !Global("Sola_Jaheira","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Jaheira","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Jan")
  !Global("Sola_Jan","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Jan","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Keldorn")
  !Global("Sola_Keldorn","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Keldorn","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Korgan")
  !Global("Sola_Korgan","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Korgan","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Mazzy")
  !Global("Sola_Mazzy","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Mazzy","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Minsc")
  !Global("Sola_Minsc","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Minsc","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Nalia")
  !Global("Sola_Nalia","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Nalia","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Sarevok")
  !Global("Sola_Sarevok","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Sarevok","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Valygar")
  !Global("Sola_Valygar","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Valygar","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  Global("SolaPickingBanterTarget","GLOBAL",1)
  Global("SolaGoingToBanter","GLOBAL",0)
  IsValidForPartyDialog("Viconia")
  !Global("Sola_Viconia","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementGlobal("Sola_Viconia","GLOBAL",1)
    SetGlobal("SolaGoingToBanter","GLOBAL",1)
END

IF
  RealGlobalTimerExpired("SolaBanter","GLOBAL")
  Global("SolaGoingToBanter","GLOBAL",0)
THEN
  RESPONSE #100
    // couldn't find anyone to talk to
    RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
    SetGlobal("SolaPickingBanterTarget","GLOBAL",0)
    // DEBUG
    DisplayString(Myself,56832) // I have seen no one. 
END


///////////////////////////////////////////////////////////////////////
// If we're in ToB, quickly change back to using the old dialogue
// files. 
///////////////////////////////////////////////////////////////////////
IF
  Global("SolaGoingToBanter","GLOBAL",1)
  GlobalGT("Chapter","GLOBAL",7)        // >7 --> in ToB
  CombatCounter(0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("SolaPickingBanterTarget","GLOBAL",0)
    SetGlobal("SolaGoingToBanter","GLOBAL",0)
    ActionOverride("Aerie",SetDialogue("BAERIE"))
    ActionOverride("Anomen",SetDialogue("BANOMEN"))
    ActionOverride("Cernd",SetDialogue("BCERND"))
    ActionOverride("Edwin",SetDialogue("BEDWIN"))
    ActionOverride("HaerDalis",SetDialogue("BHAERDA"))
    ActionOverride("Imoen2",SetDialogue("IMOEN2J"))
    ActionOverride("Jaheira",SetDialogue("BJAHEIR"))
    ActionOverride("Jan",SetDialogue("BJAN"))
    ActionOverride("Keldorn",SetDialogue("BKELDOR"))
    ActionOverride("Korgan",SetDialogue("BKORGAN"))
    ActionOverride("Mazzy",SetDialogue("BMAZZY"))
    ActionOverride("Minsc",SetDialogue("BMINSC"))
    ActionOverride("Nalia",SetDialogue("BNALIA"))
    ActionOverride("Valygar",SetDialogue("BVALYGA"))
    ActionOverride("Viconia",SetDialogue("BVICONI"))
    // Sarevok needs no change
    RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
    SetGlobal("Sola_Try_Aerie","GLOBAL",0)
    SetGlobal("Sola_Try_Anomen","GLOBAL",0)
    SetGlobal("Sola_Try_Cernd","GLOBAL",0)
    SetGlobal("Sola_Try_Edwin","GLOBAL",0)
    SetGlobal("Sola_Try_HD","GLOBAL",0)
    SetGlobal("Sola_Try_Imoen","GLOBAL",0)
    SetGlobal("Sola_Try_Jan","GLOBAL",0)
    SetGlobal("Sola_Try_Jaheira","GLOBAL",0)
    SetGlobal("Sola_Try_Keldorn","GLOBAL",0)
    SetGlobal("Sola_Try_Korgan","GLOBAL",0)
    SetGlobal("Sola_Try_Mazzy","GLOBAL",0)
    SetGlobal("Sola_Try_Minsc","GLOBAL",0)
    SetGlobal("Sola_Try_Nalia","GLOBAL",0)
    SetGlobal("Sola_Try_Valygar","GLOBAL",0)
    SetGlobal("Sola_Try_Viconia","GLOBAL",0)
    SetGlobal("Sola_Try_Sarevok","GLOBAL",0)
    StartDialogueNoSet(Player1)
END

///////////////////////////////////////////////////////////////////////
// Otherwise just banter
///////////////////////////////////////////////////////////////////////
IF
  Global("SolaGoingToBanter","GLOBAL",1)
  !GlobalGT("Chapter","GLOBAL",7)        // >7 --> in ToB
  CombatCounter(0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("SolaPickingBanterTarget","GLOBAL",0)
    SetGlobal("SolaGoingToBanter","GLOBAL",0)
    RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
    SetGlobal("Sola_Try_Aerie","GLOBAL",0)
    SetGlobal("Sola_Try_Anomen","GLOBAL",0)
    SetGlobal("Sola_Try_Cernd","GLOBAL",0)
    SetGlobal("Sola_Try_Edwin","GLOBAL",0)
    SetGlobal("Sola_Try_HD","GLOBAL",0)
    SetGlobal("Sola_Try_Imoen","GLOBAL",0)
    SetGlobal("Sola_Try_Jan","GLOBAL",0)
    SetGlobal("Sola_Try_Jaheira","GLOBAL",0)
    SetGlobal("Sola_Try_Keldorn","GLOBAL",0)
    SetGlobal("Sola_Try_Korgan","GLOBAL",0)
    SetGlobal("Sola_Try_Mazzy","GLOBAL",0)
    SetGlobal("Sola_Try_Minsc","GLOBAL",0)
    SetGlobal("Sola_Try_Nalia","GLOBAL",0)
    SetGlobal("Sola_Try_Valygar","GLOBAL",0)
    SetGlobal("Sola_Try_Viconia","GLOBAL",0)
    SetGlobal("Sola_Try_Sarevok","GLOBAL",0)
    StartDialogueNoSet(Player1)
END

///////////////////////////////////////////////////////////////////////
// Restore those TOB dialogue files
///////////////////////////////////////////////////////////////////////
IF
  Global("SolaDoneBanter","GLOBAL",1)
  GlobalGT("Chapter","GLOBAL",7)        // >7 --> in ToB
THEN
  RESPONSE #100
    SetGlobal("SolaDoneBanter","GLOBAL",0)
    ActionOverride("Aerie",SetDialogue("AERIE25J"))
    ActionOverride("Anomen",SetDialogue("ANOME25J"))
    ActionOverride("Cernd",SetDialogue("CERND25J"))
    ActionOverride("Edwin",SetDialogue("EDWIN25J"))
    ActionOverride("HaerDalis",SetDialogue("HAERD25J"))
    ActionOverride("Imoen2",SetDialogue("IMOEN25J"))
    ActionOverride("Jaheira",SetDialogue("JAHEI25J"))
    ActionOverride("Jan",SetDialogue("JAN25J"))
    ActionOverride("Keldorn",SetDialogue("KELDO25J"))
    ActionOverride("Korgan",SetDialogue("KORGA25J"))
    ActionOverride("Mazzy",SetDialogue("MAZZY25J"))
    ActionOverride("Minsc",SetDialogue("MINSC25J"))
    ActionOverride("Nalia",SetDialogue("NALIA25J"))
    ActionOverride("Valygar",SetDialogue("VALYG25J"))
    ActionOverride("Viconia",SetDialogue("VICON25J"))
    EndCutSceneMode()
    // Sarevok needs no change
END

IF
  Global("SolaDoneBanter","GLOBAL",1)
  !GlobalGT("Chapter","GLOBAL",7)        // <=7 --> in SoA
THEN
  RESPONSE #100
    SetGlobal("SolaDoneBanter","GLOBAL",0)
    EndCutSceneMode()
END


///////////////////////////////////////////////////////////////////////
// for people doing upgades from a pre-banter Sola
///////////////////////////////////////////////////////////////////////
IF 
  Global("SolaEverSetBanter","GLOBAL",0)
THEN 
  RESPONSE #100
    RealSetGlobalTimer("SolaBanter","GLOBAL",6400)
    SetGlobal("SolaEverSetBanter","GLOBAL",1)
END

///////////////////////////////////////////////////////////////////////
// The Unholy Eclipse
///////////////////////////////////////////////////////////////////////
IF
  Global("SolaEclipseWarn","GLOBAL",0)
  OR(2)
      Dead("Sendai") // Sendai
      Dead("Abazigal") // Abazigal
  OR(2)
    TimeOfDay(0)  // DAY
    TimeOfDay(3)  // MORNING
  CombatCounter(0)
  See(Player1)
  InParty(Myself)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("SolaEclipseWarn","GLOBAL",1)
    StartDialogueNoSet(Player1) // sets warn to 2
    EndCutSceneMode()
END

IF
  Global("SolaEclipseWarn","GLOBAL",2)
  TimeOfDay(2)  // night
  OR(2)
    AreaType(OUTDOOR)
    AreaType(FOREST)
  CombatCounter(0)
  InParty(Myself)
  See(Player1)
THEN
  RESPONSE #100
      IncrementGlobal("SolaEclipseWarn","GLOBAL",1)
      CreateCreatureObject("SolaSpy1",Myself,0,0,0) // No such index
END

///////////////////////////////////////////////////////////////////////
// The New Sword 
///////////////////////////////////////////////////////////////////////
IF
  HasItem("solablad",Myself)
  XPGT(Myself,3500000)
  CombatCounter(0)
  !Detect([ENEMY])
THEN
  RESPONSE #100
    StartCutSceneMode()
        Wait(1)
        ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
        Wait(1)
        DestroyItem("solablad")
        CreateVisualEffectObject("spcrtwpn",Myself)
        GiveItemCreate("SolaBla2",Myself,1,0,0)
        Wait(4)
        SetGlobal("SolaBladeUpgrade","GLOBAL",1)
        StartDialogueNoSet(Player1)
    EndCutSceneMode()
END
