/////////////////////////////////////////////////////////////////////
// Ylekilnu, 21th level Eclipse Druid
// 
// We completely ignore in-game memorization (hey, who doesn't?) and
// use global variables to keep track of spells. 
// 
// Memorized Spells By Level: 9 9 9 9 8 6 6 
// Memorized Spells (number, name, casting time): 
//
//      1 SPPR701       shield of archons       9 (prep)
//      1 nature's beauty
//      4 1717 CLERIC_CREEPING_DOOM
//      6 1605 CLERIC_CONJURE_FIRE_ELEMENTAL
//      4 1517 CLERIC_INSECT_PLAGUE
//      4 1506 CLERIC_IRONSKIN
//      9 sppr405       mental domination       4
//      9 1319 CLERIC_SUMMON_INSECTS
//      9 sppr208       hold person             5
//      9 1113 CLERIC_DOOM
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Battle Prep!
/////////////////////////////////////////////////////////////////////
IF
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
          SetGlobalTimer("Cast","LOCALS",0)
          SetGlobalTimer("CastTrue","LOCALS",0)
          GiveItemCreate("potn34",Myself,1,0,0)
          UseItem("potn34",Myself)

          SetGlobal("Beauty","LOCALS",1)
          SetGlobal("Creep","LOCALS",4)
          SetGlobal("Fire","LOCALS",6)
          SetGlobal("InsectP","LOCALS",4) 
          SetGlobal("Iron","LOCALS",4) 
          SetGlobal("Mental","LOCALS",9)
          SetGlobal("InsectS","LOCALS",9)
          SetGlobal("Hold","LOCALS",9)
          SetGlobal("Doom","LOCALS",9)

          SetGlobal("Prep","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Spell: Ironskin
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Iron","LOCALS",0)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
	  IncrementGlobal("Iron","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(Myself,CLERIC_IRONSKIN)
END

/////////////////////////////////////////////////////////////////////
// Spell: Beauty 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Beauty","LOCALS",0)
	See(NearestEnemyOfType([PC]))
	Range(NearestEnemyOfType([PC]),20)
THEN
	RESPONSE #100
	  IncrementGlobal("Beauty","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(Myself,CLERIC_NATURE_BEAUTY)
END

/////////////////////////////////////////////////////////////////////
// Spell: Creeping Doom
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Creep","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("Creep","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_CREEPING_DOOM)
END

/////////////////////////////////////////////////////////////////////
// Spell: Insect Plauge 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("InsectP","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("InsectP","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)
END

/////////////////////////////////////////////////////////////////////
// Heal!
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        HPPercentLT(Myself,80)
THEN    
        RESPONSE #100
          UseItem("potn55",Myself)
          SetGlobalTimer("Cast","LOCALS",6)
END

/////////////////////////////////////////////////////////////////////
// Spell: Fire Elemental
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Fire","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("Fire","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_CONJURE_FIRE_ELEMENTAL)
END

/////////////////////////////////////////////////////////////////////
// Spell: Mental Domination
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Mental","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Mental","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

/////////////////////////////////////////////////////////////////////
// Spell: Greater Command
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Command","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Command","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

/////////////////////////////////////////////////////////////////////
// Spell: Insect 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("InsectS","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("InsectS","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_SUMMON_INSECTS)
END


/////////////////////////////////////////////////////////////////////
// Spell: Hold Person
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Hold","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Hold","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

/////////////////////////////////////////////////////////////////////
// Spell: Doom (if nearby enemy)
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Doom","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
          IncrementGlobal("Doom","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	  SpellNoDec(LastSeenBy(Myself),CLERIC_DOOM)
END

/////////////////////////////////////////////////////////////////////
// Use those energy blades ... the half-attack or "cast and attack" method
/////////////////////////////////////////////////////////////////////
IF
  HasItem("eneblade", Myself)
  See(WorstAC)
        Allegiance(Myself,ENEMY)
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(NearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(SecondNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(ThirdNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(FourthNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Attack easy targets.
/////////////////////////////////////////////////////////////////////
IF
	See(WorstAC)
        Allegiance(Myself,ENEMY)
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack mages.
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	OR(4)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack party members.
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOfType([PC]))
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack whatever ...
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Attack Player1. 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(Player1,12)
END
