/////////////////////////////////////////////////////////////////////
// Reffus, 25th level Eclipse Cleric
// 
// We completely ignore in-game memorization (hey, who doesn't?) and
// use global variables to keep track of spells. 
// 
// Memorized Spells By Level: 9 9 9 9 9 7 3 
// Memorized Spells (number, name, casting time): 
//
//      1 SPPR727       fallen deva             5
//      1 SPPR701       shield of archons       9 (prep)
//      1 SPPR728       implosion               5
//      1               physical mirror (prep)
//      5 sPPR607       heal                    9
//      1               blade barrier (prep)    
//      4 sppr503       flame strike            8
//      4               true seeing 
//      9 sppr405       mental domination       4
//      9 sppr304       glyph of warding        9
//      9 sppr208       hold person             5
//      8 sppr109       sanctuary               4
//      1               armor of faith ...
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Battle Prep!
/////////////////////////////////////////////////////////////////////
IF
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
          SetGlobalTimer("Cast","LOCALS",0)
          SetGlobalTimer("CastTrue","LOCALS",60)
          GiveItemCreate("potn34",Myself,1,0,0)
          UseItem("potn34",Myself)

          SetGlobal("Deva","LOCALS",1)
          SetGlobal("Shield","LOCALS",1)
          SetGlobal("Implosion","LOCALS",1)
          SetGlobal("SolaE4Heal","GLOBAL",5)
          SetGlobal("Flame","LOCALS",5)
          SetGlobal("True","LOCALS",4)
          SetGlobal("Mental","LOCALS",9)
          SetGlobal("Glyph","LOCALS",9)
          SetGlobal("Hold","LOCALS",9)
          SetGlobal("Sanct","LOCALS",8)

          SetGlobal("Prep","LOCALS",1)
          ReallyForceSpell(Myself,CLERIC_TRUE_SIGHT)
END

/////////////////////////////////////////////////////////////////////
// Spell: Sanctuary (if nearby enemy)
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Sanct","LOCALS",0)
	Range(NearestEnemyOf(Myself),3)
	CheckStatLT(Myself,1,SANCTUARY)
THEN
	RESPONSE #100
          IncrementGlobal("Sanct","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	  SpellNoDec(Myself,CLERIC_SANCTUARY)
END

/////////////////////////////////////////////////////////////////////
// Spell: Heal (if nearby ally)
/////////////////////////////////////////////////////////////////////
IF
        See(Nearest([ALLY]))
        HPPercentLT(LastSeenBy(Myself),75)
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("SolaE4Heal","GLOBAL",0)
THEN
	RESPONSE #100
          IncrementGlobal("SolaE4Heal","GLOBAL",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	  SpellNoDec(LastSeenBy(Myself),CLERIC_HEAL)
END

/////////////////////////////////////////////////////////////////////
// Spell: Heal (if nearby ally)
/////////////////////////////////////////////////////////////////////
IF
        See(SecondNearest([ALLY]))
        HPPercentLT(LastSeenBy(Myself),75)
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("SolaE4Heal","GLOBAL",0)
THEN
	RESPONSE #100
          IncrementGlobal("SolaE4Heal","GLOBAL",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	  SpellNoDec(LastSeenBy(Myself),CLERIC_HEAL)
END

/////////////////////////////////////////////////////////////////////
// Spell: Heal (if nearby ally)
/////////////////////////////////////////////////////////////////////
IF
        See(ThirdNearest([ALLY]))
        HPPercentLT(LastSeenBy(Myself),75)
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("SolaE4Heal","GLOBAL",0)
THEN
	RESPONSE #100
          IncrementGlobal("SolaE4Heal","GLOBAL",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	  SpellNoDec(LastSeenBy(Myself),CLERIC_HEAL)
END


/////////////////////////////////////////////////////////////////////
// Spell: True Sight
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalTimerExpired("CastTrue","LOCALS")
	GlobalGT("True","LOCALS",0)
THEN
	RESPONSE #100
	  IncrementGlobal("True","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
          SetGlobalTimer("CastTrue","LOCALS",60)
	 SpellNoDec(Myself,CLERIC_TRUE_SIGHT)
END

/////////////////////////////////////////////////////////////////////
// Spell: Fallen Deva
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Deva","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("Deva","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),1727)
END

/////////////////////////////////////////////////////////////////////
// Spell: Implosion
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Implosion","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Implosion","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),1728)
END

/////////////////////////////////////////////////////////////////////
// Spell: Implosion
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Implosion","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Implosion","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),1728)
END

/////////////////////////////////////////////////////////////////////
// Spell: Flame Strike
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Flame","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Flame","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Flame Strike
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Flame","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Flame","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

/////////////////////////////////////////////////////////////////////
// Heal!
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        HPPercentLT(Myself,80)
THEN    
        RESPONSE #100
          UseItem("potn55",Myself)
          SetGlobalTimer("Cast","LOCALS",6)
END

/////////////////////////////////////////////////////////////////////
// Spell: Mental Domination
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Mental","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Mental","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

/////////////////////////////////////////////////////////////////////
// Spell: Greater Command
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Command","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Command","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

/////////////////////////////////////////////////////////////////////
// Spell: Glyph 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Glyph","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Glyph","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

/////////////////////////////////////////////////////////////////////
// Spell: Glyph 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Glyph","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Glyph","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

/////////////////////////////////////////////////////////////////////
// Spell: Hold Person
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Hold","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Hold","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

/////////////////////////////////////////////////////////////////////
// Use those energy blades ... the half-attack or "cast and attack" method
/////////////////////////////////////////////////////////////////////
IF
  HasItem("eneblade", Myself)
  See(WorstAC)
  !HasBounceEffects(LastSeenBy(Myself))
        Allegiance(Myself,ENEMY)
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(NearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(SecondNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(ThirdNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade", Myself)
  See(FourthNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Attack easy targets.
/////////////////////////////////////////////////////////////////////
IF
	See(WorstAC)
        Allegiance(Myself,ENEMY)
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack mages.
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	OR(4)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack party members.
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOfType([PC]))
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack whatever ...
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Attack Player1. 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(Player1,12)
END
