//////////////////////////////////////////////////////////////////////
// sola0002 
// It's this little mushroom that the Red Badge foes hang around in. They
// teleport you to it from the pocket-plane. When they are all dead 
// you can leave. 
//////////////////////////////////////////////////////////////////////
IF
  Global("RedBadgePrep","GLOBAL",0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("RedBadgePrep","GLOBAL",1)
    CreateCreature("solasna1",[756.641],0)  // snake
    CreateCreature("solasna2",[942.535],8) // caster
    CreateCreature("solasna3",[712.358],0)  // mist
    CreateCreature("solasna4",[458.621],0)  // spike
    CreateCreature("solasna5",[307.491],8) // spear
    TriggerActivation("Tran0404",FALSE)
    ActionOverride("solasna1",StartDialogueNoSet(Player1))
    EndCutSceneMode()
END

IF
  Global("RedBadgeStage","GLOBAL",2)
  Global("RedBadgeFight","GLOBAL",0)
  InMyArea(Player1)
THEN
  RESPONSE #10
    ActionOverride("solasna1",StartDialogueNoSet(Player1))
END

IF
  Dead("solasna1")
  Dead("solasna2")
  Dead("solasna3")
  Dead("solasna4")
  Dead("solasna5")
  Global("RedBadgeLeave","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RedBadgeLeave","GLOBAL",1)
    TriggerActivation("Tran0404",TRUE)
END
