/////////////////////////////////////////////////////////////////////
// Citpeks, 20th level Eclipse Sorcerer
// 
// We completely ignore in-game memorization (hey, who doesn't?) and
// use global variables to keep track of spells. 
// 
// Memorized Spells By Level: 6 6 6 6 6 6 6 6 6
// Known Spells (level, name): 
//      9 2925 WIZARD_DRAGONS_BREATH
//      9 2902 WIZARD_SPELL_TRAP
//      9 2903 WIZARD_SPELL_STRIKE
//      8 2812 WIZARD_ABI_DALZIMS_HORRID_WILTING
//      7 2716 WIZARD_MORDENKAINENS_SWORD
//      6 2611 WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
//      5 2590 WIZARD_SPELL_IMMUNITY_ABJURATION
//      5 2513 WIZARD_BREACH
//      5 2508 WIZARD_CHAOS
//      4 2408 WIZARD_STONE_SKIN
//      3 2302 WIZARD_DISPEL_MAGIC (really remove magic) 
//      3 2312 WIZARD_SLOW
//      2 2211 WIZARD_MELF_ACID_ARROW
//      1 2112 WIZARD_MAGIC_MISSILE
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Battle Prep!
/////////////////////////////////////////////////////////////////////
IF
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
          SetGlobalTimer("Cast","LOCALS",0)
          SetGlobalTimer("RecastProMagWeap","LOCALS",0)
          GiveItemCreate("potn34",Myself,1,0,0)
          UseItem("potn34",Myself)

          SetGlobal("Nine","LOCALS",6)
          SetGlobal("Eight","LOCALS",6)
          SetGlobal("Seven","LOCALS",6)
          SetGlobal("Six","LOCALS",6)
          SetGlobal("Five","LOCALS",6) 
          SetGlobal("Four","LOCALS",6) 
          SetGlobal("Three","LOCALS",6)
          SetGlobal("Two","LOCALS",6)
          SetGlobal("One","LOCALS",6)

          SetGlobal("Prep","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Chain Contingency
/////////////////////////////////////////////////////////////////////
IF
    See(NearestEnemyOfType([PC]))
    Global("ChainContingency","LOCALS",0)
THEN
  RESPONSE #100
    DisplayString(Myself,26328) // Chain Contingency
    SetGlobal("ChainContingency","LOCALS",1)
    SetGlobalTimer("RemoveTimer","LOCALS",18)
    ReallyForceSpell(NearestEnemyOfType([PC]),2302) // REMOVE_MAGIC
    ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
    ReallyForceSpell(NearestEnemyOfType([PC]),WIZARD_DRAGONS_BREATH)
END

/////////////////////////////////////////////////////////////////////
// Contingency
/////////////////////////////////////////////////////////////////////
IF
    See(NearestEnemyOf(Myself))
    TookDamage()
    Global("Contingency","LOCALS",0)
THEN
    RESPONSE #100
        DisplayString(Myself,40252) // Contingency - Protection ...
        ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("RecastProMagWeap","LOCALS",24)
        SetGlobal("Contingency","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Spell: Pro Mag Weapon (if nearby enemy or attacked)
/////////////////////////////////////////////////////////////////////
IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("RecastProMagWeap","LOCALS")
    GlobalGT("Six","LOCALS",0)
    Exists(NearestEnemyOf(Myself))
    HPPercentLT(Myself,100)
    OR(2)
      See(LastAttackerOf(Myself))
      Range(NearestEnemyOf(Myself),2)
THEN
	RESPONSE #100
	  IncrementGlobal("Six","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
          SetGlobalTimer("RecastProMagWeap","LOCALS",24)
	  SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END

/////////////////////////////////////////////////////////////////////
// Spell: Stoneskin
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Four","LOCALS",0)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
	  IncrementGlobal("Four","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(Myself,WIZARD_STONE_SKIN)
END

/////////////////////////////////////////////////////////////////////
// Spell: Immunity Abjuration
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Five","LOCALS",0)
	Global("ImmuneAbjure","LOCALS",0)
THEN
  RESPONSE #100
      IncrementGlobal("Five","LOCALS",-1)
      SetGlobal("ImmuneAbjure","LOCALS",1)
      SetGlobalTimer("Cast","LOCALS",6)
      SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
END


/////////////////////////////////////////////////////////////////////
// Spell: Spell Strike
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Nine","LOCALS",0)
        See(NearestEnemyOfType([PC]))
        HasBounceEffects(LastSeenBy(Myself))
THEN
    RESPONSE #100
	IncrementGlobal("Nine","LOCALS",-1)
        SetGlobalTimer("Cast","LOCALS",6)
	SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)
END

/////////////////////////////////////////////////////////////////////
// Anti-Mordy
/////////////////////////////////////////////////////////////////////
IF
 See([GOODCUTOFF.0.0.0.0.SUMMONED])
 CheckStatGT(LastSeenBy(Myself),99,RESISTSLASHING) // Mordy!
 GlobalTimerExpired("Cast","LOCALS")
 GlobalGT("Six","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Six","LOCALS",-1)
    SetGlobalTimer("Cast","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_FOG)
END

/////////////////////////////////////////////////////////////////////
// Spell: Dragon's Breath
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Nine","LOCALS",0)
        See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
    RESPONSE #100
	IncrementGlobal("Nine","LOCALS",-1)
        SetGlobalTimer("Cast","LOCALS",6)
	SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

/////////////////////////////////////////////////////////////////////
// Spell: Dragon's Breath
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Nine","LOCALS",0)
        See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
    RESPONSE #100
	IncrementGlobal("Nine","LOCALS",-1)
        SetGlobalTimer("Cast","LOCALS",6)
	SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

/////////////////////////////////////////////////////////////////////
// Spell: Breach 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Five","LOCALS",0)
        See(NearestEnemyOfType([PC]))
        OR(2)
          HasImmunityEffects(LastSeenBy(Myself))
	  CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
THEN
    RESPONSE #100
	IncrementGlobal("Five","LOCALS",-1)
        SetGlobalTimer("Cast","LOCALS",6)
	SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)
END

/////////////////////////////////////////////////////////////////////
// Spell: Abi
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Eight","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Eight","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

/////////////////////////////////////////////////////////////////////
// Spell: Abi
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Eight","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Eight","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

/////////////////////////////////////////////////////////////////////
// Heal!
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        HPPercentLT(Myself,80)
THEN    
        RESPONSE #100
          UseItem("potn55",Myself)
          SetGlobalTimer("Cast","LOCALS",6)
END

/////////////////////////////////////////////////////////////////////
// Spell: Mordy
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Seven","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
         IncrementGlobal("Seven","LOCALS",-1)
         SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalTimerExpired("RemoveTimer","LOCALS")
	GlobalGT("Three","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("Three","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
          SetGlobalTimer("RemoveTimer","LOCALS",18)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

/////////////////////////////////////////////////////////////////////
// Spell: Malison
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Four","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        Global("Malison","LOCALS",0)
THEN
	RESPONSE #100
	  IncrementGlobal("Four","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

/////////////////////////////////////////////////////////////////////
// Spell: Haste (catch those mordy near the PC)
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Three","LOCALS",0)
        Global("Haste","LOCALS",0)
	See(NearestEnemyOfType([PC]))
THEN
	RESPONSE #100
	  IncrementGlobal("Four","LOCALS",-1)
	  IncrementGlobal("Haste","LOCALS",1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_HASTE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Chaos
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Five","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Five","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

/////////////////////////////////////////////////////////////////////
// Spell: Slow
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Three","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
THEN
	RESPONSE #100
	  IncrementGlobal("Three","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
END

/////////////////////////////////////////////////////////////////////
// Spell: Melf
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Two","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Two","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

/////////////////////////////////////////////////////////////////////
// Spell: Melf
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("Two","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("Two","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

/////////////////////////////////////////////////////////////////////
// Spell: Magic Missile
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("One","LOCALS",0)
	See(NearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("One","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Magic Missile
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	GlobalGT("One","LOCALS",0)
	See(SecondNearestEnemyOfType([PC]))
        !HasItem("clck26",LastSeenBy(Myself))
THEN
	RESPONSE #100
	  IncrementGlobal("One","LOCALS",-1)
          SetGlobalTimer("Cast","LOCALS",6)
	 SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END


/////////////////////////////////////////////////////////////////////
// Use those energy blades ... the half-attack or "cast and attack" method
/////////////////////////////////////////////////////////////////////
IF
  HasItem("eneblade",Myself)
  See(WorstAC)
        Allegiance(Myself,ENEMY)
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade",Myself)
  See(NearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade",Myself)
  See(SecondNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade",Myself)
  See(ThirdNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END
IF
  HasItem("eneblade",Myself)
  See(FourthNearestEnemyOfType([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SelectWeaponAbility(SLOT_WEAPON1,0)
    Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Attack easy targets.
/////////////////////////////////////////////////////////////////////
IF
	See(WorstAC)
        Allegiance(Myself,ENEMY)
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack mages.
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
	OR(4)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),12)
END

/////////////////////////////////////////////////////////////////////
// Attack whatever ...
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Cast","LOCALS")
        !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
	RESPONSE #100
		Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Attack Player1. 
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(Player1,12)
END
