//////////////////////////////////////////////////////////////////////////
// Solaufein the Vampire
//////////////////////////////////////////////////////////////////////////

IF
    Die()
THEN
    RESPONSE #100
        SetGlobal("SolaVampire","GLOBAL",3)
        DropInventory()
        DestroySelf()
END

IF
  AreaCheck("AR0800")
THEN
  RESPONSE #100
        CreateVisualEffectObject("SPDIMNDR",Myself)
        SetGlobal("SolaVampire","GLOBAL",2)
        MoveBetweenAreas("ar0809",[1473.332],2)
END

//////////////////////////////////////////////////////////////////////////
// Initialize
//////////////////////////////////////////////////////////////////////////
IF
    Allegiance(Myself,NEUTRAL)
    HasItem("ring07","c6bodhi") // it's the Improved Bodhi
    OR(3)
      Global("C6BodhiFight","AR0809",1)
      AttackedBy([ANYTHING],DEFAULT)
      SpellCastOnMe([ANYTHING],0)
THEN
  RESPONSE #100
    // the PCs deserve an extra reward for fighting against Sola *and* the
    // Improved Bodhi ... but they'll have to kill us to get it!
    GiveItemCreate("clck02",Myself,1,0,0)  // cloak of protection +2
    // this cloak's description talks about vampires -- cute!
    Continue()
END

IF
    Allegiance(Myself,NEUTRAL)
    OR(3)
      Global("C6BodhiFight","AR0809",1)
      AttackedBy([ANYTHING],DEFAULT)
      SpellCastOnMe([ANYTHING],0)
THEN
    RESPONSE #100
        Enemy()
        // defend against Sunray, False Dawn
        SetGlobal("Cast","LOCALS",0)

        SetGlobal("Missile","LOCALS",5) // 1
        SetGlobal("Acid","LOCALS",5)    // 2
        SetGlobal("Remove","LOCALS",5)  // 3

        DisplayString(Myself,25951) // Sequencer
        ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE) // 4
        ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED) // 4
        ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) // 4
        SetGlobal("Stoneskin","LOCALS",1) // 4

        DisplayString(Myself,40252) // Contingency
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS) // 6
        SetGlobalTimer("ProMagic","LOCALS",24)
        SetGlobal("ProMagicNum","LOCALS",2) // 6

        ReallyForceSpell(Myself,WIZARD_MORDENKAINENS_SWORD) // 7

        ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD) // 5
        DisplayString(Myself,26328) // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION) // 5
        ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION) // 5
        ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION) // 5

        // Lolth likes us now!
        DisplayString(Myself,60762) // In Lolth's Name!
        CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
        CreateCreatureObjectDoor("solaspi",Player1,0,0,0)
END

/////////////////////////////////////////////////////////////////////
// Stall
/////////////////////////////////////////////////////////////////////
IF
    Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
        // do nothing
END

/////////////////////////////////////////////////////////////////////
// Second Wind
/////////////////////////////////////////////////////////////////////
IF
    HPPercentLT(Myself,50)
    Global("SecondWind","LOCALS",0)
    !Difficulty(EASIEST)
THEN
  RESPONSE #100
    SetGlobal("SecondWind","LOCALS",1)
    DisplayString(Myself,60762) // In Lolth's Name!
    CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
    CreateCreatureObjectDoor("solaspi",Myself,0,0,0)
    ReallyForceSpell(Myself,CLERIC_HEAL)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    ReallyForceSpell(Myself,WIZARD_TIME_STOP)
    SetGlobalTimer("ProMagic","LOCALS",24)
END

/////////////////////////////////////////////////////////////////////
// Pro-Magery
/////////////////////////////////////////////////////////////////////
IF
    GlobalGT("ProMagicNum","LOCALS",0)
    HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("ProMagic","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        IncrementGlobal("ProMagicNum","LOCALS",-1)
        SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

/////////////////////////////////////////////////////////////////////
// Spell: Stoneskin (if out)
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("Cast","LOCALS")
        GlobalGT("Stoneskin","LOCALS",0)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
          SetGlobalTimer("Cast","LOCALS",6)
          IncrementGlobal("Stoneskin","LOCALS",-1)
          SpellNoDec(Myself,WIZARD_STONE_SKIN)
END

/////////////////////////////////////////////////////////////////////
// Move in for the kill 
/////////////////////////////////////////////////////////////////////
IF
  !Detect([PC])
  Delay(6)
THEN
  RESPONSE #100
    ReallyForceSpell(Player1,PHASE_SPIDER_TELEPORT)
    ReallyForceSpell(Player1,WIZARD_TRUE_SIGHT)
END

/////////////////////////////////////////////////////////////////////
// Target!
/////////////////////////////////////////////////////////////////////
IF
    OR(3) 
      See(NearestEnemyOfType([PC]))
      See(WorstAC)
      See(LastAttackerOf(Myself))
    False()
THEN
    RESPONSE #100
END

/////////////////////////////////////////////////////////////////////
// Remove Magic
/////////////////////////////////////////////////////////////////////
IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalGT("Remove","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        IncrementGlobal("Remove","LOCALS",-1)
        SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
    RESPONSE #100
        // sometimes do nothing, fall through
END

/////////////////////////////////////////////////////////////////////
// Melf Acid Arrow 
/////////////////////////////////////////////////////////////////////
IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalGT("Acid","LOCALS",0)
    CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        IncrementGlobal("Acid","LOCALS",-1)
        SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

/////////////////////////////////////////////////////////////////////
// Magic Missile
/////////////////////////////////////////////////////////////////////
IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalGT("Missile","LOCALS",0)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        IncrementGlobal("Missile","LOCALS",-1)
        SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

/////////////////////////////////////////////////////////////////////
// Move in for the kill 
/////////////////////////////////////////////////////////////////////
IF
  !Allegiance(LastSeenBy(Myself),ENEMY)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),VAMPIRE_FEAR)
    ReallyForceSpell(LastSeenBy(Myself),VAMPIRE_DOMINATION)
    Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Move in for the kill 
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),VAMPIRE_FEAR)
    ReallyForceSpell(LastSeenBy(Myself),VAMPIRE_DOMINATION)
    Attack(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// wander
/////////////////////////////////////////////////////////////////////
IF
  True()
THEN
  RESPONSE #100
    RandomWalkContinuous()
END
