////////////////////////////////////////////////////////////////////
// Solaufein Revenge Spider script.
// 
// These guys actually aren't that complicated. :-)
////////////////////////////////////////////////////////////////////

// when I fall, my comrades grow stronger
IF
  Die()
  See(SecondNearest([ENEMY.0.SPIDER]))
THEN
  RESPONSE #100
    DisplayString(SecondNearest([ENEMY.0.SPIDER]),@80) 
    ReallyForceSpellDead(SecondNearest([ENEMY.0.SPIDER]),CLERIC_HEAL)
    ReallyForceSpellDead(SecondNearest([ENEMY.0.SPIDER]),WIZARD_IMPROVED_HASTE)
END

// if we haven't webbed the party yet, do so!
IF
  See(NearestEnemyOf(Myself))
  Global("SolaSpiWeb","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SolaSpiWeb","LOCALS",1)
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_WEB)
END

// go for easily-slain victims first 
IF
  ActionListEmpty()
  See(WorstAC)
THEN
  RESPONSE #100
    AttackReevaluate(WorstAC,10)
END

// if all else fails, bash someone!
IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),10)
END
