////////////////////////////////////////////////////////////////////
// AR2100 extension for Solaufein
// Make Sola appear if the party has done all of the right things. 
////////////////////////////////////////////////////////////////////
IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatGT(Player1,1500000,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola17",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END

IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatGT(Player1,1250000,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola15",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END

IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatGT(Player1,1000000,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola12",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END

IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatGT(Player1,750000,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola10",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END

IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatGT(Player1,500000,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola7",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END

IF
	GlobalGT("SolaufeinJob","GLOBAL",8)
	Global("spawnSol3","GLOBAL",0)
	GlobalGT("PhaereJob","GLOBAL",9)
	Global("SolaJoin","GLOBAL",0)
	CheckStatLT(Player1,500001,XP)
	!Dead("Solaufein")
	!Dead("Sola")
THEN
	RESPONSE #100
		CreateCreatureDoor("sola5",[4844.339],4)
		SetGlobal("spawnSol3","GLOBAL",1)
END
