name: 'Solaufein Mod Packager'

on:
  release:
    types: [published]

jobs:
  call_workflow:
    permissions:
      contents: write
    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: multi
      naming: ini
      tp2_name: 'setup-solaufeinEE.tp2'
      suffix: version
